Repository excellaco/tcp-angular, pull requests merged in 2019-06, with the labels that each got.

#62 Documentation
  README.md
Labels: documentation, enhancement

#68 Tests for Category Management under Admin section
  package.json
  src/app/admin/admin-panel/admin-panel.component.html
  src/app/admin/admin-panel/admin-panel.component.scss
  src/app/admin/admin-panel/admin-panel.component.spec.ts
  src/app/admin/admin-panel/admin-panel.component.ts
  src/app/admin/admin-routing.module.ts
  src/app/admin/admin.module.ts
  src/app/admin/manage-categories/category-form/category-form.component.html
  src/app/admin/manage-categories/category-form/category-form.component.spec.ts
  src/app/admin/manage-categories/category-form/category-form.unit.spec.ts
  src/app/admin/manage-categories/category-list/category-list.component.html
  src/app/admin/manage-categories/manage-categories.component.spec.ts
  src/app/admin/manage-categories/manage-categories.component.ts
  src/app/admin/manage-categories/manage-categories.unit.spec.ts
  src/app/app.module.ts
  src/app/employee/employee-list/employee-list.component.html
  src/app/employee/employee-list/employee-list.component.spec.ts
  src/app/employee/employee-list/employee-list.component.ts
  src/app/home/home.component.html
  src/app/home/home.component.spec.ts
  src/app/pipes/required-message/required-message.pipe.spec.ts
  src/app/pipes/required-message/required-message.pipe.ts
Labels: enhancement

#69 tests: Fix required message pipe issues
  src/app/admin/manage-categories/category-form/category-form.component.spec.ts
  src/app/employee/employee-form/employee-form.component.ts
  src/app/pipes/required-message/required-message.pipe.spec.ts
  src/app/pipes/required-message/required-message.pipe.ts
Labels: bug

#74 Data table enhancements
  angular.json
  src/app/admin/manage-categories/category-form/category-form.component.spec.ts
  src/app/employee/employee-form/contact-form/contact-form.component.html
  src/app/employee/employee-list/employee-list.component.html
  src/app/employee/employee-list/employee-list.component.scss
  src/app/employee/employee-list/employee-list.component.ts
  src/app/employee/employee-list/list-controls/list-controls.component.html
  src/app/employee/employee-list/list-controls/list-controls.component.scss
  src/app/employee/employee-list/list-controls/list-controls.component.spec.ts
  src/app/employee/employee-list/list-controls/list-controls.component.ts
  src/app/employee/employee.module.ts
  src/app/login/login.component.html
  src/app/main-nav/main-nav.component.html
  src/app/material.module.ts
  src/app/pipes/required-message/required-message.pipe.spec.ts
  src/app/services/employees/employees.service.fake.ts
  src/theme.scss
Labels: enhancement

#78 add required markers
  src/app/employee/employee-form/bio-form/bio-form.component.html
  src/app/employee/employee-form/contact-form/address-form/address-form.component.html
Labels: bug

#79 Skill filtering
  karma.conf.js
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/employee/employee-form/skills-form/skill-detail/skill-detail.component.ts
  src/app/employee/employee-list/employee-list.component.html
  src/app/employee/employee-list/employee-list.component.spec.ts
  src/app/employee/employee-list/employee-list.component.ts
  src/app/employee/employee-list/employee-list.component.unit.spec.ts
  src/app/employee/employee-list/list-controls/list-controls.component.html
  src/app/employee/employee-list/list-controls/list-controls.component.spec.ts
  src/app/employee/employee-list/list-controls/list-controls.component.ts
  src/app/employee/employee-list/list-controls/list-controls.component.unit.spec.ts
  src/app/employee/employee.module.ts
  src/app/models/skill.interface.ts
  src/app/services/auth/auth.service.fake.ts
  src/app/services/employees/employees.service.fake.ts
Labels: INSTALL REQ'D, enhancement

#80 Admin category updates
  src/app/admin/admin.module.ts
  src/app/admin/manage-categories/category-form/category-form.unit.spec.ts
  src/app/admin/manage-categories/category-list/category-list.component.html
  src/app/admin/manage-categories/category-list/category-list.component.spec.ts
  src/app/admin/manage-categories/category-list/category-list.component.ts
  src/app/admin/manage-categories/confirm-category-delete/confirm-category-delete.component.html
  src/app/admin/manage-categories/confirm-category-delete/confirm-category-delete.component.ts
  src/app/admin/manage-categories/manage-categories.component.spec.ts
  src/app/admin/manage-categories/manage-categories.component.ts
  src/app/admin/manage-categories/manage-categories.component.unit.spec.ts
  src/app/employee/employee-form/contact-form/address-form/address-form.component.html
  src/app/employee/employee-list/employee-list.component.html
  src/app/employee/employee-list/employee-list.component.spec.ts
  src/app/employee/employee-list/employee-list.component.ts
  src/app/employee/employee-list/employee-list.component.unit.spec.ts
  src/app/employee/employee-list/list-controls/list-controls.component.html
  src/app/employee/employee-list/list-controls/list-controls.component.spec.ts
  src/app/employee/employee-list/list-controls/list-controls.component.unit.spec.ts
  src/app/employee/employee.module.ts
  src/app/login/login.component.unit.spec.ts
  src/app/material.module.ts
  src/app/services/auth/auth.service.integration.spec.ts
Labels: enhancement

#75 Delicious toasts on saving info
  src/app/material.module.ts
  src/app/services/employees/employees.service.ts
  src/app/services/skill-categories/skill-categories.service.ts
  src/app/services/skills/skills.service.ts
  src/app/services/snack-bar/snack-bar.service.spec.ts
  src/app/services/snack-bar/snack-bar.service.ts
Labels: enhancement

#85 Messaging
  src/app/admin/admin.module.ts
  src/app/admin/manage-categories/confirm-category-delete/confirm-category-delete.component.html
  src/app/admin/manage-categories/confirm-category-delete/confirm-category-delete.component.ts
  src/app/admin/manage-categories/manage-categories.component.spec.ts
  src/app/admin/manage-categories/manage-categories.component.ts
  src/app/admin/manage-categories/manage-categories.component.unit.spec.ts
  src/app/app.module.ts
  src/app/home/chart/chart.component.html
  src/app/home/home.component.html
  src/app/home/home.component.spec.ts
  src/app/home/home.component.ts
  src/app/home/home.component.unit.spec.ts
  src/app/material.module.ts
  src/app/messaging/confirmation-dialog/confirmation-dialog.component.html
  src/app/messaging/confirmation-dialog/confirmation-dialog.component.ts
  src/app/messaging/messaging.module.ts
  src/app/messaging/services/dialog/dialog.service.fake.ts
  src/app/messaging/services/dialog/dialog.service.spec.ts
  src/app/messaging/services/dialog/dialog.service.ts
  src/app/messaging/services/snack-bar/snack-bar.service.spec.ts
  src/app/messaging/services/snack-bar/snack-bar.service.ts
  src/app/services/employees/employees.service.fake.ts
  src/app/services/employees/employees.service.spec.ts
  src/app/services/employees/employees.service.ts
  src/app/services/skill-categories/skill-categories.service.spec.ts
  src/app/services/skill-categories/skill-categories.service.ts
  src/app/services/skills/skills.service.fake.ts
  src/app/services/skills/skills.service.spec.ts
  src/app/services/skills/skills.service.ts
  src/app/services/snack-bar/snack-bar.service.spec.ts
Labels: enhancement

#84 Age restriction
  package.json
  src/app/admin/manage-categories/manage-categories.component.spec.ts
  src/app/admin/manage-categories/manage-categories.component.unit.spec.ts
  src/app/employee/employee-form/bio-form/bio-form.component.html
  src/app/employee/employee-form/bio-form/bio-form.component.ts
  src/app/utils/date.validators.ts
  src/app/utils/date.validators.unit.spec.ts
Labels: bug

#87 Primary Skill restriction to only one primary skill
  src/app/admin/manage-categories/manage-categories.component.spec.ts
  src/app/employee/employee-form/skills-form/skill-detail/skill-detail.component.html
  src/app/employee/employee-form/skills-form/skill-detail/skill-detail.component.spec.ts
  src/app/employee/employee-form/skills-form/skill-detail/skill-detail.component.ts
  src/app/employee/employee-form/skills-form/skills-form.component.html
  src/app/employee/employee.module.ts
  src/app/employee/services/primary-skill/primary-skill.service.spec.ts
  src/app/employee/services/primary-skill/primary-skill.service.ts
Labels: enhancement

#91 Fix NPM security concern
  package-lock.json
Labels: Security

#88 WIP: Service Refactor (with Material SnackBar)
  src/app/admin/manage-categories/category-form/category-form.component.spec.ts
  src/app/admin/manage-categories/category-form/category-form.component.ts
  src/app/admin/manage-categories/category-form/category-form.unit.spec.ts
  src/app/admin/manage-categories/category-list/category-list.component.spec.ts
  src/app/admin/manage-categories/category-list/category-list.component.ts
  src/app/admin/manage-categories/manage-categories.component.spec.ts
  src/app/admin/manage-categories/manage-categories.component.ts
  src/app/admin/manage-categories/manage-categories.component.unit.spec.ts
  src/app/admin/manage-skills/manage-skills.component.spec.ts
  src/app/admin/manage-skills/manage-skills.component.ts
  src/app/admin/manage-skills/skill-form/skill-form.component.spec.ts
  src/app/admin/manage-skills/skill-form/skill-form.component.ts
  src/app/admin/manage-skills/skill-list/skill-list.component.spec.ts
  src/app/admin/manage-skills/skill-list/skill-list.component.ts
  src/app/app-routing.module.ts
  src/app/employee/employee-form/bio-form/bio-form.component.spec.ts
  src/app/employee/employee-form/bio-form/bio-form.component.ts
  src/app/employee/employee-form/contact-form/address-form/address-form.component.spec.ts
  src/app/employee/employee-form/contact-form/contact-form.component.spec.ts
  src/app/employee/employee-form/employee-form.component.spec.ts
  src/app/employee/employee-form/skills-form/skill-detail/skill-detail.component.spec.ts
  src/app/employee/employee-form/skills-form/skill-detail/skill-detail.component.ts
  src/app/employee/employee-form/skills-form/skills-form.component.spec.ts
  src/app/employee/employee-list/employee-list.component.spec.ts
  src/app/employee/employee-list/employee-list.component.ts
  src/app/employee/employee-list/employee-list.component.unit.spec.ts
  src/app/employee/employee-list/list-controls/list-controls.component.spec.ts
  src/app/employee/employee-list/list-controls/list-controls.component.ts
  src/app/employee/employee-list/list-controls/list-controls.component.unit.spec.ts
  src/app/employee/self-service/self-service.component.spec.ts
  src/app/employee/self-service/self-service.component.ts
  src/app/messaging/services/dialog/dialog.service.spec.ts
  src/app/messaging/services/snack-bar/snack-bar.service.fake.ts
  src/app/messaging/services/snack-bar/snack-bar.service.spec.ts
  src/app/messaging/services/snack-bar/snack-bar.service.ts
  src/app/services/abstract/base-crud.service.ts
  src/app/services/employees/employees.service.fake.ts
  src/app/services/employees/employees.service.spec.ts
  src/app/services/employees/employees.service.ts
  src/app/services/skill-categories/skill-categories.service.fake.ts
  src/app/services/skill-categories/skill-categories.service.spec.ts
  src/app/services/skill-categories/skill-categories.service.ts
  src/app/services/skills/skills.service.fake.ts
  src/app/services/skills/skills.service.spec.ts
  src/app/services/skills/skills.service.ts
Labels: enhancement

#97 Jenkins
  Jenkinsfile
  src/app/admin/manage-categories/manage-categories.component.html
  src/environments/environment.prod.ts
Labels: enhancement
